"""
photo_storage.py - Meter photo storage

Deliberately simple: photos are written to a folder on the server's own disk,
not to a cloud bucket. That keeps the feature free to run and removes the
AWS credential/config burden, while still meeting the requirement that the
photo is durable evidence attached to the reading.

Security model:
    - Files are stored OUTSIDE any static-served directory and are never given
      a public URL. The only way to see a photo is through the authorised
      /photo endpoints in app.py, which check that the caller is either the
      tenant who submitted it or an admin.
    - Stored filenames are generated by us (never derived from the client's
      filename), so a malicious upload name cannot traverse directories or
      overwrite an existing file.
    - Uploads are validated by magic bytes, not just extension, so renaming
      evil.exe to evil.jpg does not get it accepted.

Swapping to S3 later means reimplementing save()/read()/delete() here; nothing
in app.py depends on the fact that this is local disk.
"""

import os
import re
import uuid
from datetime import datetime
from typing import Tuple

from log import get_logger

logger = get_logger("app")


class PhotoValidationError(Exception):
    """Raised when an uploaded file is not an acceptable meter photo."""


class PhotoStorageError(Exception):
    """Raised when the file could not be written to or read from disk."""


# Magic byte signatures -> canonical extension + mime type.
_SIGNATURES = (
    (b"\xff\xd8\xff",                 "jpg",  "image/jpeg"),
    (b"\x89PNG\r\n\x1a\n",            "png",  "image/png"),
)

_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]")


def _detect(content: bytes) -> Tuple[str, str]:
    """
    Identify the image from its leading bytes.
    Returns (extension, mime). Raises PhotoValidationError if unrecognised.
    """
    for signature, ext, mime in _SIGNATURES:
        if content.startswith(signature):
            return ext, mime
    # WebP: "RIFF....WEBP"
    if content[:4] == b"RIFF" and content[8:12] == b"WEBP":
        return "webp", "image/webp"
    raise PhotoValidationError(
        "That file does not look like a photo. Please upload a JPG, PNG or WebP image."
    )


def validate(content: bytes, original_name: str, allowed_types: str, max_mb: int) -> Tuple[str, str]:
    """
    Check an uploaded file before it is stored.

    allowed_types is the comma-separated admin setting (e.g. "jpg,jpeg,png").
    Returns (extension, mime_type) on success.
    """
    if not content:
        raise PhotoValidationError("The uploaded file is empty.")

    max_bytes = max_mb * 1024 * 1024
    if len(content) > max_bytes:
        actual_mb = len(content) / (1024 * 1024)
        raise PhotoValidationError(
            f"Photo is {actual_mb:.1f} MB, which is over the {max_mb} MB limit. "
            "Please take the photo at a lower resolution or compress it."
        )

    # A real image is never this small; catches truncated/corrupt uploads.
    if len(content) < 100:
        raise PhotoValidationError("The photo appears to be corrupted or incomplete.")

    ext, mime = _detect(content)

    allowed = {e.strip().lower() for e in (allowed_types or "").split(",") if e.strip()}
    # jpg and jpeg are the same format - accept either spelling in the setting.
    if ext == "jpg" and ("jpg" in allowed or "jpeg" in allowed):
        pass
    elif ext not in allowed:
        raise PhotoValidationError(
            f"{ext.upper()} photos are not accepted. Allowed: {', '.join(sorted(allowed)).upper()}."
        )

    return ext, mime


def build_key(shop_id: int, meter_id: int, ext: str, when: datetime = None) -> str:
    """
    Relative storage key, e.g.
        shop-4/meter-7/2026/08/20260813-a3f9c1e2.jpg

    Date-partitioned so a folder never accumulates an unmanageable number of
    files, and prefixed by shop/meter so photos for one meter are easy to find
    (and easy to archive) on disk.
    """
    when = when or datetime.now()
    unique = uuid.uuid4().hex[:12]
    return (
        f"shop-{int(shop_id)}/meter-{int(meter_id)}/"
        f"{when:%Y}/{when:%m}/{when:%Y%m%d}-{unique}.{ext}"
    )


def _full_path(base_dir: str, key: str) -> str:
    """
    Resolve a storage key to an absolute path, refusing anything that escapes
    the configured base directory (defence in depth - keys are generated by us,
    but this also protects the read path if a bad key ever reaches the DB).
    """
    base = os.path.abspath(base_dir)
    target = os.path.abspath(os.path.join(base, key))
    if not target.startswith(base + os.sep) and target != base:
        raise PhotoStorageError("Invalid photo location.")
    return target


def save(base_dir: str, key: str, content: bytes) -> str:
    """Write the photo to disk. Returns the storage key that was used."""
    target = _full_path(base_dir, key)
    try:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        # "xb" - never silently overwrite existing evidence.
        with open(target, "xb") as fh:
            fh.write(content)
    except FileExistsError:
        raise PhotoStorageError("A photo already exists at that location.")
    except OSError as exc:
        logger.error("Failed writing meter photo to %s: %s", target, exc)
        raise PhotoStorageError("Could not save the photo on the server.") from exc
    return key


def read(base_dir: str, key: str) -> bytes:
    """Read a stored photo back. Raises PhotoStorageError if it is gone."""
    target = _full_path(base_dir, key)
    if not os.path.isfile(target):
        raise PhotoStorageError("The photo file is missing from the server.")
    try:
        with open(target, "rb") as fh:
            return fh.read()
    except OSError as exc:
        logger.error("Failed reading meter photo %s: %s", target, exc)
        raise PhotoStorageError("Could not read the photo from the server.") from exc


def exists(base_dir: str, key: str) -> bool:
    try:
        return os.path.isfile(_full_path(base_dir, key))
    except PhotoStorageError:
        return False


def safe_original_name(name: str) -> str:
    """
    Keep the customer's filename for display/audit only, stripped of anything
    that could be dangerous. It is never used to build a path.
    """
    if not name:
        return ""
    cleaned = _SAFE_NAME.sub("_", os.path.basename(name))
    return cleaned[:255]
